# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, loginDialog):
        loginDialog.setObjectName("loginDialog")
        loginDialog.resize(383, 126)
        self.verticalLayout = QtWidgets.QVBoxLayout(loginDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(loginDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.loginLine = QtWidgets.QLineEdit(loginDialog)
        self.loginLine.setObjectName("loginLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.loginLine)
        self.label_2 = QtWidgets.QLabel(loginDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.passwdLine = QtWidgets.QLineEdit(loginDialog)
        self.passwdLine.setObjectName("passwdLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwdLine)
        self.verticalLayout.addLayout(self.formLayout)
        self.loginBtn = QtWidgets.QPushButton(loginDialog)
        self.loginBtn.setObjectName("loginBtn")
        self.verticalLayout.addWidget(self.loginBtn)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.regBtn = QtWidgets.QPushButton(loginDialog)
        self.regBtn.setObjectName("regBtn")
        self.horizontalLayout.addWidget(self.regBtn)
        self.recBtn = QtWidgets.QPushButton(loginDialog)
        self.recBtn.setObjectName("recBtn")
        self.horizontalLayout.addWidget(self.recBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(loginDialog)
        QtCore.QMetaObject.connectSlotsByName(loginDialog)

    def retranslateUi(self, loginDialog):
        _translate = QtCore.QCoreApplication.translate
        loginDialog.setWindowTitle(_translate("loginDialog", "Вход"))
        self.label.setText(_translate("loginDialog", "Логин"))
        self.label_2.setText(_translate("loginDialog", "Пароль"))
        self.loginBtn.setText(_translate("loginDialog", "Вход"))
        self.regBtn.setText(_translate("loginDialog", "Регистрация"))
        self.recBtn.setText(_translate("loginDialog", "Забыли пароль?"))
