# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/forms/login_rec.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginRecDialog(object):
    def setupUi(self, LoginRecDialog):
        LoginRecDialog.setObjectName("LoginRecDialog")
        LoginRecDialog.resize(390, 110)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginRecDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(LoginRecDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.loginLine = QtWidgets.QLineEdit(LoginRecDialog)
        self.loginLine.setObjectName("loginLine")
        self.horizontalLayout.addWidget(self.loginLine)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.okBtn = QtWidgets.QPushButton(LoginRecDialog)
        self.okBtn.setObjectName("okBtn")
        self.verticalLayout.addWidget(self.okBtn)

        self.retranslateUi(LoginRecDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginRecDialog)

    def retranslateUi(self, LoginRecDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginRecDialog.setWindowTitle(_translate("LoginRecDialog", "Dialog"))
        self.label.setText(_translate("LoginRecDialog", "Введите ваш логин:"))
        self.okBtn.setText(_translate("LoginRecDialog", "OK"))
