from PyQt5 import QtCore, QtWidgets


class Ui_RegisterDialog(object):
    def setupUi(self, RegisterDialog):
        RegisterDialog.setObjectName("RegisterDialog")
        RegisterDialog.resize(570, 175)
        self.verticalLayout = QtWidgets.QVBoxLayout(RegisterDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(RegisterDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.loginLine = QtWidgets.QLineEdit(RegisterDialog)
        self.loginLine.setObjectName("loginLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.loginLine)
        self.label_2 = QtWidgets.QLabel(RegisterDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.passwdLine = QtWidgets.QLineEdit(RegisterDialog)
        self.passwdLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwdLine.setObjectName("passwdLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwdLine)
        self.label_3 = QtWidgets.QLabel(RegisterDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.passwdRepLine = QtWidgets.QLineEdit(RegisterDialog)
        self.passwdRepLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwdRepLine.setObjectName("passwdRepLine")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.passwdRepLine)
        self.label_4 = QtWidgets.QLabel(RegisterDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.queryLine = QtWidgets.QLineEdit(RegisterDialog)
        self.queryLine.setObjectName("queryLine")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.queryLine)
        self.label_5 = QtWidgets.QLabel(RegisterDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.answLine = QtWidgets.QLineEdit(RegisterDialog)
        self.answLine.setObjectName("answLine")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.answLine)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.regBtn = QtWidgets.QPushButton(RegisterDialog)
        self.regBtn.setObjectName("regBtn")
        self.horizontalLayout.addWidget(self.regBtn)
        self.loginBtn = QtWidgets.QPushButton(RegisterDialog)
        self.loginBtn.setObjectName("loginBtn")
        self.horizontalLayout.addWidget(self.loginBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(RegisterDialog)
        QtCore.QMetaObject.connectSlotsByName(RegisterDialog)

    def retranslateUi(self, RegisterDialog):
        _translate = QtCore.QCoreApplication.translate
        RegisterDialog.setWindowTitle(_translate("RegisterDialog", "Регистрация"))
        self.label.setText(_translate("RegisterDialog", "Логин"))
        self.label_2.setText(_translate("RegisterDialog", "Пароль"))
        self.label_3.setText(_translate("RegisterDialog", "Повторите пароль"))
        self.label_4.setText(_translate("RegisterDialog", "Контрольный вопрос (если забудете пароль)"))
        self.label_5.setText(_translate("RegisterDialog", "Ответ на контрольный вопрос"))
        self.regBtn.setText(_translate("RegisterDialog", "Регистрация"))
        self.loginBtn.setText(_translate("RegisterDialog", "Вход"))
